# Generated by Django 5.2 on 2025-04-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
