# Generated by Django 5.2 on 2025-05-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_alter_news_sub_title_alter_news_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Comment',
            new_name='comments',
        ),
    ]
