# Generated by Django 5.2 on 2025-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
